---
# tasks file for backend
- name: Clone yolo Application Git repository
  git:
    repo: "{{ gitrepo_url }}"
    dest: "{{ dest_folder }}"
    version: master
    update: yes
  tags: git

  - name: Install Docker and Docker Compose
    apt:
      name: ['docker.io', 'docker-compose']
      state: present

  - name: Ensure the backend container is running.
    docker_container:
      image: backend:latest
      name: backend
      state: started